services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DATABASE_PATH: /app/data/db.sqlite
      MIGRATIONS_DIR: /app/internal/db/migrations
      ALLOWED_ORIGIN: http://localhost:5173
      BASE_ADDRESS: "0.0.0.0"
    volumes:
      - uploads_data:/app/uploads
      - sqlite_data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend


volumes:
  uploads_data:
  sqlite_data:
